-- Add order_number column with auto-increment starting at 100000
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000);

-- Create index for faster lookups by order number
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders (order_number);

-- Note: Existing rows will automatically get values backfilled due to the IDENTITY property
